### ISSUE TITLE
Support for matrix linear transformation visualization

### ISSUE THREAD

**Issue by tompurker** [rage/secret-project-331#1132]
Add support for content matrix manipulation to let students manipulate an image through changing matrix values.

- To be used at the end of [this page](https://courses.mooc.fi/org/uh-mathstat/courses/johdatus-matriisilaskentaan/chapter-8) (before exercises)
- How it worked on the [old platform](https://rage.github.io/introduction-to-matrix-calculus/2-lineaarikuvaus)

**Comment by nygrenh** [comment]
![Image](https://github.com/rage/secret-project-331/assets/1922896/fafd4397-a65b-491d-b04c-4317c937c3e0)
