### ISSUE TITLE
Point export

### ISSUE THREAD

**Issue by nygrenh** [rage/secret-project-331#209]
For each course instance provide a button that exports points breakdown to csv

Something like this: https://tmc.mooc.fi/org/test/courses/301/points

From this table grouped by chapters: https://github.com/rage/secret-project-331-db-docs/blob/master/public.user_exercise_states.md

Should stream the results: https://github.com/rage/mooc.fi/blob/master/backend/api/completions.ts#L65

Downloads:

Change browser document.location to the download url -> triggers download.

**Comment by Heliozoa** [comment]
SELECT ch.id, u.id, COALESCE(sum(ues.score_given), 0) as score_given
FROM user_exercise_states ues
LEFT JOIN courses c ON c.id = '816ecbd6-74e4-4a6e-9620-207c2d1bcdad'
LEFT JOIN organizations o ON o.id = c.organization_id
LEFT JOIN users u ON u.id = ues.user_id
LEFT JOIN exercises e ON e.id = ues.exercise_id
LEFT JOIN pages p ON p.id = e.page_id
LEFT JOIN chapters ch ON ch.id = p.chapter_id
WHERE ues.course_instance_id = 'b42bf303-e73e-4eb4-a448-5890754cc313'
GROUP BY ch.id, u.id
