### ISSUE TITLE
Design for peer reviews

### ISSUE THREAD

**Issue by nygrenh** [rage/secret-project-331#380]
Answering:
![Screenshot from 2021-09-20 17-05-12](https://user-images.githubusercontent.com/1922896/134016707-5e6b468f-5225-4603-8eea-5a83fe0c41e1.png)

Selecting which one to review:

![Screenshot from 2021-09-20 17-10-14](https://user-images.githubusercontent.com/1922896/134017074-8046dd86-0ebf-4550-8e40-c519d05feac5.png)

Reviewing:

![Screenshot from 2021-09-20 17-08-48](https://user-images.githubusercontent.com/1922896/134016940-65ff165a-9437-4c4b-bbeb-d4fd76501010.png)
)

**Comment by george-misan** [comment]
General comment section; they're only +ve feedbacks, no neutral, or negative feedbacks (was it done on purpose?)
